### ISSUE TITLE
红米7手机：相机授权后闪退

### ISSUE THREAD

**Issue by q88qaz** [MZCretin/ScanCode#1]
E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.lskj.lszbar, PID: 27476
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lskj.lszbar-dL67-9Wk6FFCDYiNawI7Rg==/base.apk"],nativeLibraryDirectories=[/data/app/com.lskj.lszbar-dL67-9Wk6FFCDYiNawI7Rg==/lib/arm64, /system/lib64]]] couldn't find "libZBarDecoder.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.dtr.zbar.build.ZBarDecoder.<clinit>(ZBarDecoder.java:6)
        at com.cretin.tools.scancode.decode.DecodeHandler.<init>(DecodeHandler.java:38)
        at com.cretin.tools.scancode.decode.DecodeThread.run(DecodeThread.java:59)

**Comment by q88qaz** [comment]
将gradle版本从3.5.0将为3.4.0问题解决

**Comment by q88qaz** [comment]
将gradle版本从3.5.0降为3.4.0问题解决
